### ISSUE TITLE
It's Can working on win10 right?

### ISSUE THREAD

**Issue by qw1324** [moonD4rk/HackBrowserData#36]

**Comment by moonD4rk** [comment]
Because this security tool calls win32 API in the execution process, so it will be `windows defender` or other antivirus software as a virus, I will provide a simple way to bypass in version 0.26, and then no longer provide the corresponding bypass strategy. The core code is open source, you can compile your own.

**Comment by qw1324** [comment]
> Because this security tool calls win32 API in the execution process, so it will be `windows defender` or other antivirus software as a virus, I will provide a simple way to bypass in version 0.26, and then no longer provide the corresponding bypass strategy. The core code is open source, you can compile your own.

how to use it do have course？

**Comment by moonD4rk** [comment]
Give me more details.
