### ISSUE TITLE
Cookies/password decrypt in chrome/chromium 88

### ISSUE THREAD

**Issue by eduardohayashi** [moonD4rk/HackBrowserData#76]
**Describe the bug**
描述一下遇到的 Bug，和对应的报错信息 `./hack-browser-data -vv`
Hi
It isnt decrypting Cookies and Password values in Google Chrome 88 and Brave 1.19.92 (Chromium: 88)

![d251113d-384f-492c-a510-f7fe043a669e](https://user-images.githubusercontent.com/3841825/107783660-6eda4700-6d42-11eb-971b-018fb8a6750f.jpeg)

In firefox it works fine 

**Desktop (please complete the following information):**
 - OS Name 操作系统名称: Debian Buster
 - Browser Name 浏览器名称: Google Chrome and Chromium
 - Browser Version 浏览器版本: 88

**Additional context**
其他有用的信息

**Comment by moonD4rk** [comment]
Thanks for the information, can you use `./hack-browser-data -b chrome -vv` and give me the corresponding verbose information.

**Comment by eduardohayashi** [comment]
Follow
```
$ ./hack-browser-data -b chrome -vv
cmd.go:68: error No such interface “org.freedesktop.DBus.Properties” on object at path /org/freedesktop/secrets/collection/login
browser.go:152: debug Chrome find bookmark File Success
browser.go:152: debug Chrome find cookie File Success
browser.go:152: debug Chrome find history File Success
browser.go:152: debug Chrome find download File Success
browser.go:152: debug Chrome find password File Success
browser.go:152: debug Chrome find creditcard File Success
[x]:  Get 370 bookmarks, filename is results/chrome_bookmark.csv 
[x]:  Get 364 cookies, filename is results/chrome_cookie.csv 
[x]:  Get 4189 history, filename is results/chrome_history.csv 
[x]:  Get 138 download history, filename is results/chrome_download.csv 
[x]:  Get 65 passwords, filename is results/chrome_password.csv 
[x]:  Get 0 credit cards, filename is results/chrome_credit.csv
```
The result is the same for cookies value and password
```
$ cat results/chrome_cookie.csv 
Host,Path,KeyName,Value,IsSecure,IsHTTPOnly,HasExpire,IsPersistent,CreateDate,ExpireDate
github.com,/,_gh_sess,,true,true,false,false,2020-09-19T14:57:25.987443Z,1601-01-01T00:00:00Z
github.com,/,_octo,,true,false,true,true,2020-08-15T11:10:44.17748Z,2021-08-15T11:10:44Z
.github.com,/,logged_in,,true,true,true,true,2020-09-19T14:57:25.987513Z,2021-09-19T14:57:25.987513Z
.github.com,/,_ga,,false,false,true,true,2020-08-15T11:10:42.622618Z,2022-09-23T16:08:15Z
```

```
$ cat results/chrome_password.csv
UserName,Password,LoginUrl,CreateDate
admin,,http://192.168.25.193:9000/,2019-07-11T16:03:26.133824Z
admin,,http://192.168.25.193:8080/login,2019-06-06T08:56:02.578413Z
,,https://trello.com/,2019-05-31T10:07:59.565636Z
,,https://mail.google.com/,2019-05-29T09:14:03.204389Z
```

**Comment by telethonic** [comment]
First of all, thanks for providing such a great tool :)

I'm seeing the same issue, trying to get chrome passwords on Centos 7:

`#133 20:38:53 -> ./hack-browser-data -b chrome --vv
cmd.go:68: error dbus secret key is empty
browser.go:152: debug Chrome find bookmark File Success
browser.go:152: debug Chrome find cookie File Success
browser.go:152: debug Chrome find history File Success
browser.go:152: debug Chrome find download File Success
browser.go:152: debug Chrome find password File Success
browser.go:152: debug Chrome find creditcard File Success
[x]:  Get 3429 bookmarks, filename is results/chrome_bookmark.csv 
[x]:  Get 664 cookies, filename is results/chrome_cookie.csv 
[x]:  Get 5988 history, filename is results/chrome_history.csv 
[x]:  Get 58 download history, filename is results/chrome_download.csv 
[x]:  Get 1002 passwords, filename is results/chrome_password.csv 
[x]:  Get 0 credit cards, filename is results/chrome_credit.csv 
`

Running the go file as suggested in https://github.com/moonD4rk/HackBrowserData/issues/32
(issue 32) produces:

`#138 20:57:41 -> go run main.go
secret label is: 
secret label is: 
secret label is: 
`

I think I always cancelled the "keyring prompts" that Chrome used to give me.

Chrome itself still has the passwords and auto-fills them fine, but they seem to be no longer accessible since Google appears to have switched to "View and manage saved passwords in your Google account" (when I go to passwords.google.com, there is 1 (one) password there (?!)).

Any pointers will be much appreciated..

**Comment by moonD4rk** [comment]
Sorry for the late reply, please check this link to see if you can see the password option. I think your problem is a Linux problem, you can try to sync chrome data to Windows or Mac and then export the corresponding password.
`chrome://settings/passwords?search=saved+passwords`
